### ISSUE TITLE
fix: Issue in index file

### ISSUE THREAD

**Issue by AdityaSinha2305** [GarimaSingh0109/Resum-Resume#772]
There is an issue in index file same piece of code written multiple times.
Can you assign me this under 'gssoc-ext' ?

**Comment by Abhishek-Sharma-069** [comment]
There is an issue in index file same piece of code written multiple times.
Here you can see multiple head , body and style tags are used. 
Here i want to change in index.html file and in global.css file for same features like nav bar that are common in all pages.
![Screenshot (188)](https://github.com/user-attachments/assets/27c5143b-2498-4425-a1ae-10722aa8aae8)
![Screenshot (187)](https://github.com/user-attachments/assets/91baf523-7cf5-400b-9f6c-accb0c2e2a36)

Could you assign this task to me, So that I can start working on it.
Please make sure to add labels gssoc-ext, hactoberfest, level1, level2, level3
