### ISSUE TITLE
Fix Overlapping Footer Issue on Login Page

### ISSUE THREAD

**Issue by saumyasri123** [GarimaSingh0109/Resum-Resume#993]
The login page currently has a significant issue where the footer overlaps with the login form, making it difficult for users to interact with the fields and buttons. This overlap affects the overall user experience and can prevent users from successfully logging in.

**Proposed Solution:**
Adjust CSS Styles: Review and modify the CSS styles for the login page to ensure that the footer is positioned correctly and does not overlap with the login form.
Use Flexbox or Grid: Consider utilizing CSS Flexbox or Grid layout techniques to create a more responsive design that accommodates varying screen sizes and prevents overlap.
Testing Across Devices: Ensure that the changes are tested across different devices and screen sizes to verify that the login page is fully functional and visually appealing.
Implementing these changes will enhance user experience and ensure that the login functionality is accessible and easy to use. I would be happy to assist in fixing this issue as I am contributor of GirlScript Summer of Code!
![Screenshot 2024-11-06 005749](https://github.com/user-attachments/assets/0e559d2e-ef80-4442-a854-d36aed320edb)

**Comment by LavkushSolanki** [comment]
hello @saumyasri123  i have fixed up this following issues here is the screen shot 
![Screenshot (416)](https://github.com/user-attachments/assets/fe9e4a42-d5d4-4138-9820-e3a220e47554)
![Screenshot (417)](https://github.com/user-attachments/assets/94d0da6e-6a81-4009-af8a-c984cc25d690)
![Screenshot (418)](https://github.com/user-attachments/assets/14ac23f8-e86a-4811-a54c-2cb4458aae0e)

I have aligned the social icon links
I have made the About and Service together  and Support and Social links together so that they will take less space in the page
